server:
  port: 8000
spring:
  application:
    name: app_gateway
  zipkin:
    base-url: http//localhost:9411
  cloud:
    gateway:
      routes:
        - id: tournament
          uri: lb://TOURNAMENT
          predicates:
            - Path=/api/v1/tournament/**
        - id: league
          uri: lb://LEAGUE
          predicates:
            - Path=/api/v1/league/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true