server:
  port: 8761
  error:
    include-binding-errors: always
    include-message: always
Spring:
  application:
    name: eureka_server
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false