services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: tarenda
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    volumes:
      - mongodb:/data/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tarenda
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - mongo_network
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=tarenda
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongo

networks:
  postgres:
    driver: bridge
  mongo_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb: {}