services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: tarenda
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mongo_network
    volumes:
      - mongodb:/data/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tarenda
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - mongo_network
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=tarenda
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongo

  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

#  eureka-server:
#    image: tapiwazireva/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#
#  appgw:
#    image: tapiwazireva/appgw:latest
#    container_name: appgw
#    ports:
#      - "8000:8000"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#
#  tournament:
#    image: tapiwazireva/tournament:latest
#    container_name: tournament
#    ports:
#      - "8001:8001"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#  league:
#    image: tapiwazireva/league:latest
#    container_name: league
#    ports:
#      - "8002:8002"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#      - appgw

networks:
  postgres:
    driver: bridge
  mongo_network:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb: {}