server:
  port: 8001
  error:
    include-binding-errors: always
    include-message: always
spring:
  application:
    name: tournament
  datasource:
    username: 'tarenda'
    url: jdbc:postgresql://localhost:5432/tournament
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http//localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true